import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { join, relative } from 'node:path';
import { describe, expect, it } from 'vitest';
import { extractDocRefs } from '../../src/tools/quality/verify-docs.js';

/**
 * Doc-to-code path guard (TRA-1023).
 *
 * `readme-claims` guards published numbers and `tools-index` guards the tool
 * listing, but nothing checked that a path a page points at still exists. A
 * rename leaves a confident-looking, wrong sentence on a public page, and until
 * now only a human reading the page found it — which is exactly how TRA-762 and
 * TRA-880 were caught.
 *
 * Paths only. Backticked *identifiers* are checked by the same extractor
 * (`verify_docs`, both directions), but prose legitimately backticks
 * non-code strings, so the symbol half is measured before it gates anything —
 * the measurement lives in `ops/docs-audit.md`.
 */

const REPO_ROOT = join(import.meta.dirname, '..', '..');

/**
 * Prefixes that name real repository files. A path outside them is a URL path,
 * an example in someone else's tree, or a runtime location — none of which this
 * repo can vouch for.
 */
const OUR_PREFIXES = [
  'src/',
  'tests/',
  'scripts/',
  'packages/',
  'docs/',
  'ops/',
  'benchmarks/',
  'skills/',
  'hooks/',
  'plans/',
  '.github/',
];

/**
 * Paths under those prefixes that belong to *another* project's tree.
 * `docs/comparisons.md` and the `/vs/` pages quote competitor source layouts;
 * those paths are real, just not here. Prefix-shaped rather than exact so a
 * further source read of the same peer needs no edit.
 *
 * A prefix here would also silence a path of ours created under the same name,
 * so the assertion below fails when one of these starts to exist here.
 */
const FOREIGN_PREFIXES = [
  'src/budget.rs', // LeanKG
  'src/mcp/', // LeanKG, Repomix, codegraph
  'src/gateway/', // SDL-MCP
  'src/serena/', // Serena
  'src/solidlsp/', // Serena
  'src/roam/', // Roam-Code
  'src/core/', // Repomix
  'src/cli/cliTokenBudget.ts', // Repomix — exact file, `src/cli/` is ours
  'src/codegraphcontext/', // CodeGraphContext
  'src/constants.ts', // SocratiCode
  'src/services/', // SocratiCode
  'src/graph/', // Graft
  'src/claude/', // Graft
  'src/hosts/', // Graft
  'src/executor.ts', // Context Mode
  'src/server.ts', // Context Mode
  'src/http/client.ts', // hypothetical file in the reader's own repo
  'docs/mcp-tools.md', // Roam-Code
  'docs/tool-enforcement.md', // SDL-MCP
  'docs/tool-output-contract.md', // SDL-MCP
  'benchmarks/cross-repo-l1/', // Roam-Code
  'src/jcodemunch_mcp/', // jCodeMunch
  'src/tokensave/', // TokenSave
  'src/accounting/', // TokenSave
  'src/extraction_worker.rs', // TokenSave
  'src/extraction/', // TokenSave
  'benchmarks/agent-eval/', // Roam-Code
  'benchmarks/METHODOLOGY.md', // jCodeMunch
  'benchmarks/README.md', // jCodeMunch
  'docs/04-evaluation/', // Serena
  'docs/BENCHMARK.md', // codebase-memory-mcp
  'docs/EVALUATION_PLAN.md', // codebase-memory-mcp
];

/**
 * Ours, absent from a checkout, and correctly written that way. A pure
 * existence check cannot tell these from drift — the reason is what separates
 * them, so it is required here rather than implied by a bare path.
 */
const EXPECTED_ABSENT: Record<string, string> = {
  'docs/_data/savings.yml': 'generated by scripts/refresh-savings.mjs, not committed',
  'docs/_site': 'Jekyll build output, gitignored',
  'ops/arrivals.md': 'moved to trace-mcp-private on 2026-09-05',
  'ops/user-signal.md': 'moved to trace-mcp-private on 2026-09-05',
  'scripts/apply-pending-update.mjs': 'named as deleted — the sentence is about its removal',
  'tests/frameworks/my-framework.test.ts': 'placeholder in the add-a-plugin instructions',
  'src/indexer/plugins/language/my-lang': 'placeholder in the add-a-plugin instructions',
};

function markdownFiles(dir: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.name.startsWith('.') || entry.name === 'node_modules') continue;
    const full = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...markdownFiles(full));
    else if (entry.name.endsWith('.md')) out.push(full);
  }
  return out;
}

function brokenPaths(rel: string, markdown: string): string[] {
  return (
    extractDocRefs(markdown)
      .filter((r) => r.kind === 'path' && OUR_PREFIXES.some((p) => r.token.startsWith(p)))
      // `src/gateway/` is written both ways in prose and arrives here without its
      // trailing slash, so the prefix has to match the directory itself.
      .filter(
        (r) =>
          !FOREIGN_PREFIXES.some(
            (p) => r.token.startsWith(p) || `${r.token}/` === p || r.token === p.replace(/\/$/, ''),
          ),
      )
      .filter((r) => !(r.token in EXPECTED_ABSENT))
      .filter((r) => !existsSync(join(REPO_ROOT, r.token)))
      .map((r) => `${rel}:${r.line} — \`${r.token}\`${r.heading ? ` (in "${r.heading}")` : ''}`)
  );
}

describe('backticked repository paths in the docs exist', () => {
  const files = [join(REPO_ROOT, 'README.md'), ...markdownFiles(join(REPO_ROOT, 'docs'))];

  it.each(files.map((f) => relative(REPO_ROOT, f)))('%s', (rel) => {
    expect(brokenPaths(rel, readFileSync(join(REPO_ROOT, rel), 'utf-8'))).toEqual([]);
  });

  it('fails on a broken src/ reference, and only on that one', () => {
    const md = ['## Storage', '', '`src/db/store.ts` reads `src/db/gone.ts`.'].join('\n');
    expect(brokenPaths('docs/x.md', md)).toEqual(['docs/x.md:3 — `src/db/gone.ts` (in "Storage")']);
  });

  it.each(FOREIGN_PREFIXES)('foreign prefix does not shadow our own tree: %s', (prefix) => {
    expect(
      existsSync(join(REPO_ROOT, prefix)),
      `${prefix} exists here now — narrow it to the exact foreign file`,
    ).toBe(false);
  });

  // An exception that outlives its reason is how an allowlist stops being read.
  it.each(Object.entries(EXPECTED_ABSENT))('exception is still needed: %s (%s)', (token) => {
    expect(existsSync(join(REPO_ROOT, token)), `${token} exists now — drop the exception`).toBe(
      false,
    );
  });
});
