#!/usr/bin/env tsx
/**
 * TRA-880: what do trace-mcp *responses* cost in tokens?
 *
 * The advertised-surface side of the token story is measured and guarded
 * (`preset-surface-budget.test.ts`). The response side never was: `src/savings.ts`
 * scores every call against a hand-written `RAW_COST_ESTIMATES` table and a flat
 * `COMPRESSION_RATIO = 0.15`, so the "tokens saved" number it reports is
 * `calls x constant` and carries no measurement at all.
 *
 * This drives the real built server over stdio on a real repo, calls each tool
 * with representative arguments, and prints the token cost of what actually
 * comes back next to what savings.ts assumes.
 *
 * Run after `pnpm run build`:
 *   npx tsx scripts/bench-response-tokens.ts [repoPath]
 */
import { spawn } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { join } from 'node:path';
import { encode } from 'gpt-tokenizer/encoding/o200k_base';
import { DEFAULT_DAEMON_PORT } from '../src/global.js';
import { estimateTokens } from '../src/utils/token-counter.js';
import { measuredBuild } from './measured-build.js';

const REPO = fileURLToPath(new URL('..', import.meta.url));
const TARGET = process.argv[2] ?? REPO;

/**
 * TRA-993: the frame is no longer written here.
 *
 * `search_text`, `get_outline` and `search` are 76% of the weight in this
 * metric, and TRA-985 showed that whoever writes their basket writes the
 * headline: three defensible hand-built frames priced the same commit at 21.0%,
 * 30.7% and 56.0%. So the basket now comes from
 * `benchmarks/response-tokens/frame.json` — generated by
 * `scripts/gen-response-token-frame.mjs`, frozen, committed before the run that
 * uses it, every stratum rule re-checked against the repository by
 * `tests/docs/response-token-frame.test.ts`. Editing the frame is a visible act
 * in its own commit, not a line moved inside a harness.
 */
interface Frame {
  queries: Array<{ q: string; stratum: string }>;
  files: Array<{ path: string; stratum: string }>;
}
const FRAME: Frame = JSON.parse(
  readFileSync(join(REPO, 'benchmarks/response-tokens/frame.json'), 'utf8'),
);
const SEARCH_BASKET = FRAME.queries.map((q) => q.q);
const OUTLINE_BASKET = FRAME.files.map((f) => f.path);
/**
 * TRA-1049: `find_usages` was priced from one hand-picked symbol
 * (`estimateTokens`), and that one sample is what put it on the over-baseline
 * list. Its cost is decided by how many incoming edges the target happens to
 * have, which varies by two orders of magnitude across a repo — the same
 * one-sample defect TRA-993 fixed for the three volume-heavy tools. It now
 * runs over the frame's committed `identifier` stratum: real symbol names,
 * picked positionally, resolved to a symbol_id by `search` at run time. No new
 * selection rule and no new frame entry — the basket is the one already frozen
 * and already re-checked by `tests/docs/response-token-frame.test.ts`.
 */
const USAGE_BASKET = FRAME.queries.filter((q) => q.stratum === 'identifier').map((q) => q.q);

/** Tool + args, ordered by real call volume from `~/.trace/savings.json`. */
const CALLS: Array<{
  tool: string;
  args: Record<string, unknown>;
  warmup?: boolean;
  /** Warmup whose first `symbol_id` becomes `$USAGE_SYMBOL` for the next call. */
  captureUsageSymbol?: boolean;
  /** Rows sharing a group collapse into one row holding their mean. */
  group?: string;
  /** The frame item this call priced — retained per item in the artifact. */
  item?: string;
}> = [
  // Not measured: the session DB is seeded per-session, so index in-session to
  // make the run self-contained instead of depending on a prior `trace index`.
  { tool: 'reindex', args: {}, warmup: true },
  // Not measured: resolves a real symbol_id for the symbol-scoped tools below.
  {
    tool: 'search',
    args: { query: 'estimateTokens', kind: 'function', limit: 1 },
    warmup: true,
  },
  ...SEARCH_BASKET.map((query) => ({
    tool: 'search_text',
    args: { query },
    group: 'search_text',
    item: query,
  })),
  ...OUTLINE_BASKET.map((path) => ({
    tool: 'get_outline',
    args: { path },
    group: 'get_outline',
    item: path,
  })),
  ...SEARCH_BASKET.map((query) => ({
    tool: 'search',
    args: { query },
    group: 'search',
    item: query,
  })),
  { tool: 'get_symbol', args: { symbol_id: '$SYMBOL' } },
  ...USAGE_BASKET.flatMap((name) => [
    {
      tool: 'search',
      args: { query: name, limit: 1 },
      warmup: true,
      captureUsageSymbol: true,
    },
    {
      tool: 'find_usages',
      args: { symbol_id: '$USAGE_SYMBOL' },
      group: 'find_usages',
      item: name,
    },
  ]),
  { tool: 'get_project_map', args: {} },
  { tool: 'get_index_health', args: {} },
  { tool: 'get_tests_for', args: { symbol_id: '$SYMBOL' } },
  { tool: 'get_context_bundle', args: { symbol_id: '$SYMBOL' } },
  {
    tool: 'get_task_context',
    args: { task: 'reduce tool response token cost' },
  },
  { tool: 'get_call_graph', args: { symbol_id: '$SYMBOL' } },
  { tool: 'get_complexity_report', args: {} },
  // TRA-945: the tail. The twelve above are 88% of recorded calls; these are the
  // next thirteen by volume, taking coverage to 97%.
  // TRA-1107: `register_edit` was priced from one hand-picked file
  // (`src/savings.ts`, which fires four duplication warnings at 351 tokens).
  // Its response is bookkeeping plus one `_duplication_warnings` entry per
  // similarity the file happens to carry, so the cost is decided by the
  // argument — the same one-sample defect TRA-993 fixed for the three
  // volume-heavy tools and TRA-1049 for `find_usages`. It runs over the frame's
  // committed `file` stratum, the same basket `get_outline` uses. No new
  // selection rule and no new frame entry.
  ...OUTLINE_BASKET.map((path) => ({
    tool: 'register_edit',
    args: { file_path: path },
    group: 'register_edit',
    item: path,
  })),
  { tool: 'reindex', args: {} },
  {
    tool: 'get_feature_context',
    args: { description: 'tool response token cost' },
  },
  { tool: 'get_env_vars', args: {} },
  { tool: 'get_dead_code', args: {} },
  { tool: 'get_changed_symbols', args: {} },
  { tool: 'check_quality_gates', args: {} },
  { tool: 'get_circular_imports', args: {} },
  { tool: 'check_duplication', args: { name: 'estimateTokens' } },
  { tool: 'check_claudemd_drift', args: {} },
  { tool: 'scan_security', args: { rules: ['all'] } },
  { tool: 'list_projects', args: {} },
  // TRA-1159: priced at 10 433 tokens by the field tail (20.9x its baseline) —
  // the most expensive single response in the product, and unmeasured until it
  // showed up there. Guarded here so the shaping cannot silently come back.
  { tool: 'get_plugin_registry', args: {} },
];

interface Row {
  tool: string;
  ok: boolean;
  chars: number;
  est: number;
  real: number;
  ms: number;
  item?: string;
  /**
   * How many results the response reported, where it reports one. A frame item
   * that matches nothing is cheap and useless at the same time — retained so a
   * reader can tell a low per-item cost from a query the corpus does not answer.
   */
  hits?: number;
}

/**
 * Collapse every grouped row into one row holding the group's mean. Mean, not
 * median: the aggregate multiplies this by a call count, so it has to be the
 * average cost of a call.
 */
function collapseGroups(rows: Array<Row & { group?: string }>): Row[] {
  const out: Row[] = [];
  const groups = new Map<string, Array<Row & { group?: string }>>();
  for (const r of rows) {
    if (!r.group) {
      out.push(r);
      continue;
    }
    (groups.get(r.group) ?? groups.set(r.group, []).get(r.group)!).push(r);
  }
  const mean = (xs: number[]): number => Math.round(xs.reduce((a, b) => a + b, 0) / xs.length);
  for (const [, rs] of groups) {
    out.push({
      tool: rs[0].tool,
      ok: rs.every((r) => r.ok),
      chars: mean(rs.map((r) => r.chars)),
      est: mean(rs.map((r) => r.est)),
      real: mean(rs.map((r) => r.real)),
      ms: mean(rs.map((r) => r.ms)),
    });
  }
  return out;
}

function run(): Promise<Array<Row & { group?: string }>> {
  return new Promise((resolve, reject) => {
    // `--preset full` rather than TRACE_MCP_PRESET: the flag is applied before
    // the config loads, so it holds whatever the machine's global config says.
    // TRACE_MCP_NO_DAEMON only disables auto-*spawn*; a session still attaches
    // to a daemon that is already running, and answers at that daemon's preset
    // (TRA-951). bench-local-only.mjs makes the daemon port unreachable for
    // this child alone, so the run measures the surface it asked for on any
    // machine — with or without a daemon up.
    const server = spawn(
      'node',
      [
        '--import',
        pathToFileURL(join(REPO, 'scripts/bench-local-only.mjs')).href,
        join(REPO, 'dist/cli.js'),
        'serve',
        '--preset',
        'full',
      ],
      {
        cwd: TARGET,
        env: {
          ...process.env,
          TRACE_MCP_NO_DAEMON: '1',
          TRACE_MCP_BENCH_BLOCK_PORT: String(DEFAULT_DAEMON_PORT),
        },
        stdio: ['pipe', 'pipe', 'inherit'],
      },
    );
    const send = (m: unknown): void => void server.stdin.write(`${JSON.stringify(m)}\n`);
    const rows: Array<Row & { group?: string }> = [];
    const timer = setTimeout(() => {
      server.kill();
      reject(new Error('timed out'));
    }, 900_000);

    let i = 0;
    let started = 0;
    let symbolId = '';
    // Separate from `symbolId` on purpose: the usage basket re-captures on every
    // item, and sharing one variable would silently re-target `get_tests_for`,
    // `get_context_bundle` and `get_call_graph` further down the run.
    let usageSymbolId = '';
    const next = (): void => {
      if (i >= CALLS.length) {
        clearTimeout(timer);
        server.kill();
        resolve(rows);
        return;
      }
      started = Date.now();
      const c = CALLS[i];
      const args: Record<string, unknown> = {};
      for (const [k, v] of Object.entries(c.args)) {
        if (v === '$SYMBOL') args[k] = symbolId;
        else if (v === '$USAGE_SYMBOL') args[k] = usageSymbolId;
        else args[k] = v;
      }
      send({
        jsonrpc: '2.0',
        id: 100 + i,
        method: 'tools/call',
        params: { name: c.tool, arguments: args },
      });
    };

    let buf = '';
    server.stdout.on('data', (chunk) => {
      buf += chunk;
      let nl: number;
      while ((nl = buf.indexOf('\n')) >= 0) {
        const line = buf.slice(0, nl);
        buf = buf.slice(nl + 1);
        if (!line.trim()) continue;
        let msg: {
          id?: number;
          result?: { content?: Array<{ text?: string }>; isError?: boolean };
        };
        try {
          msg = JSON.parse(line);
        } catch {
          continue;
        }
        if (msg.id === 1) {
          send({ jsonrpc: '2.0', method: 'notifications/initialized' });
          next();
          continue;
        }
        if (typeof msg.id === 'number' && msg.id >= 100) {
          const text = msg.result?.content?.map((c) => c.text ?? '').join('') ?? '';

          const seenSymbolId = /"symbol_id"\s*:\s*"([^"]+)"/.exec(text)?.[1] ?? '';
          symbolId ||= seenSymbolId;
          // Assigned unconditionally: a query the corpus cannot resolve must
          // clear the id and fail the next call loudly, not silently re-price
          // the previous basket item twice.
          if (CALLS[i].captureUsageSymbol) usageSymbolId = seenSymbolId;
          if (msg.result?.isError) console.error(`  [${CALLS[i].tool}] ${text.slice(0, 300)}`);
          if (!CALLS[i].warmup)
            rows.push({
              tool: CALLS[i].tool,
              ok: !msg.result?.isError,
              chars: text.length,
              est: estimateTokens(text),
              real: encode(text).length,
              ms: Date.now() - started,
              group: CALLS[i].group,
              item: CALLS[i].item,
              hits: Number(/"(?:total_matches|total)"\s*:\s*(\d+)/.exec(text)?.[1] ?? Number.NaN),
            });
          i += 1;
          next();
        }
      }
    });
    send({
      jsonrpc: '2.0',
      id: 1,
      method: 'initialize',
      params: {
        protocolVersion: '2024-11-05',
        capabilities: {},
        clientInfo: { name: 'bench-response-tokens', version: '1' },
      },
    });
  });
}

// TRA-945: three sessions, median per tool. A single sample is not a
// measurement here — `get_task_context` moved 5 383 -> 8 357 tokens between two
// runs minutes apart on the same commit, because the answer depends on index
// state, not only on the code. The median is what gets published; the spread is
// printed so a reader can see it.
const RUNS = Number(process.env.BENCH_RUNS ?? 3);
const samples = new Map<string, Row[]>();
// TRA-993: per-item measurements are kept, not just the basket mean. A mean over
// a 17x spread reads like a measurement and hides that the frame, not the tool,
// is deciding the number — so the artifact carries every item's own cost.
const itemSamples = new Map<string, Row[]>();
for (let n = 0; n < RUNS; n += 1) {
  const raw = await run();
  for (const r of raw) {
    if (!r.ok) {
      throw new Error(
        `[${r.tool}] returned an error — the preset or the index is wrong for this run, ` +
          'and a number measured on a degraded surface is worse than none. Fix, then re-run.',
      );
    }
    if (r.item) {
      const key = `${r.tool}\u0000${r.item}`;
      (itemSamples.get(key) ?? itemSamples.set(key, []).get(key)!).push(r);
    }
  }
  for (const r of collapseGroups(raw)) {
    (samples.get(r.tool) ?? samples.set(r.tool, []).get(r.tool)!).push(r);
  }
}

const median = (xs: number[]): number => {
  const s = [...xs].sort((a, b) => a - b);
  return s.length % 2
    ? s[(s.length - 1) / 2]
    : Math.round((s[s.length / 2 - 1] + s[s.length / 2]) / 2);
};
const items = [...itemSamples.entries()].map(([key, rs]) => {
  const [tool, item] = key.split('\u0000');
  return {
    tool,
    item,
    real: median(rs.map((r) => r.real)),
    real_min: Math.min(...rs.map((r) => r.real)),
    real_max: Math.max(...rs.map((r) => r.real)),
    chars: median(rs.map((r) => r.chars)),
    hits: Number.isNaN(rs[0].hits) ? undefined : median(rs.map((r) => r.hits ?? 0)),
  };
});
const rows = [...samples.entries()].map(([tool, rs]) => ({
  tool,
  ok: true,
  chars: median(rs.map((r) => r.chars)),
  est: median(rs.map((r) => r.est)),
  real: median(rs.map((r) => r.real)),
  ms: median(rs.map((r) => r.ms)),
  runs: rs.length,
  real_min: Math.min(...rs.map((r) => r.real)),
  real_max: Math.max(...rs.map((r) => r.real)),
}));

const pad = (s: string | number, n: number): string => String(s).padEnd(n);
console.log(
  `\n${pad('tool', 24)}${pad('chars', 10)}${pad('est(c/4)', 10)}${pad('o200k', 10)}${pad('min-max', 16)}${pad('ms', 8)}`,
);
for (const r of rows) {
  console.log(
    `${pad(r.tool, 24)}${pad(r.chars, 10)}${pad(r.est, 10)}${pad(r.real, 10)}${pad(`${r.real_min}-${r.real_max}`, 16)}${pad(r.ms, 8)}`,
  );
}
const total = rows.reduce((a, r) => a + r.real, 0);
console.log(`\nmedian of ${RUNS} runs; total o200k tokens across ${rows.length} tools: ${total}`);
writeFileSync(
  join(REPO, 'docs/perf/response-tokens.json'),
  `${JSON.stringify(
    {
      measured_at: new Date().toISOString(),
      // TRA-920: the build this ran at travels with the number to every surface.
      measured_build: measuredBuild(),
      target: TARGET === REPO ? 'self' : TARGET,
      runs: RUNS,
      // TRA-993: the frame this ran on, so a re-measurement is distinguishable
      // from a re-framing without diffing two harness revisions.
      frame: {
        source: 'benchmarks/response-tokens/frame.json',
        queries: SEARCH_BASKET,
        files: OUTLINE_BASKET,
        usage_symbols: USAGE_BASKET,
      },
      rows,
      items,
    },
    null,
    2,
  )}\n`,
);
