#!/usr/bin/env tsx
/**
 * TRA-1951 — run the Benchmark Lab battery headlessly and write the docs data file.
 *
 *   tsx scripts/bench-lab.ts [projectRoot] [--out docs/_data/benchmark_lab.json]
 *
 * The project is indexed into a temp DB (no registry writes, no daemon), the
 * pinned recall-harness battery runs over the three Lab arms, and the curated
 * record lands in `docs/_data/benchmark_lab.json` — the only numbers the
 * vs/* pages may quote. Machine-local paths are stripped before writing:
 * what ships is the build, the battery hash, and the aggregates.
 *
 * This is the same command the docs pages cite for re-running the figures.
 */

import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadConfig } from '../src/config.js';
import { initializeDatabase } from '../src/db/schema.js';
import { Store } from '../src/db/store.js';
import { IndexingPipeline } from '../src/indexer/pipeline.js';
import { PluginRegistry } from '../src/plugin-api/registry.js';
import { runLab } from '../src/benchmark-lab/runner.js';

const ROOT = fileURLToPath(new URL('..', import.meta.url));

function arg(name: string): string | undefined {
  const i = process.argv.indexOf(name);
  return i >= 0 ? process.argv[i + 1] : undefined;
}

/** First positional arg is the project root; `--out <path>` takes a value. */
function positional(): string | undefined {
  const args = process.argv.slice(2);
  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--out') {
      i++;
      continue;
    }
    if (!args[i].startsWith('-')) return args[i];
  }
  return undefined;
}

const target = path.resolve(positional() ?? ROOT);
const outPath = path.resolve(
  arg('--out') ?? path.join(ROOT, 'docs', '_data', 'benchmark_lab.json'),
);

async function indexTemp(projectRoot: string): Promise<{ dbPath: string; cleanup: () => void }> {
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'trace-bench-lab-'));
  const dbPath = path.join(tmp, 'index.db');
  const configResult = await loadConfig(projectRoot);
  if (configResult.isErr()) {
    throw new Error(`loadConfig failed for ${projectRoot}: ${JSON.stringify(configResult.error)}`);
  }
  const db = initializeDatabase(dbPath);
  const pipeline = new IndexingPipeline(
    new Store(db),
    PluginRegistry.createWithDefaults(),
    configResult.value,
    projectRoot,
  );
  await pipeline.indexAll(false);
  db.close();
  return { dbPath, cleanup: () => fs.rmSync(tmp, { recursive: true, force: true }) };
}

const { dbPath, cleanup } = await indexTemp(target);
try {
  const run = await runLab({ projectRoot: target, dbPath });
  const doc = {
    _comment:
      'Generated by `tsx scripts/bench-lab.ts` (TRA-1951) — do not edit by hand. ' +
      'Every Benchmark Lab figure the site quotes reads from here. Tokens are exact ' +
      '(o200k_base) over the pinned recall-harness battery; the file-reading arm is ' +
      'the index-free control. Re-run with the same command and compare battery sha.',
    generated_at: run.finished_at,
    measured_build: run.measured_build,
    measured_on: "trace-mcp's own repository",
    battery: run.battery,
    model: run.model,
    arms: run.aggregates,
    per_fixture: run.results,
  };
  // The battery dir is a machine-local checkout path — the sha is the
  // comparability contract, the path is not.
  delete (doc.battery as { fixtures_dir?: string }).fixtures_dir;
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, `${JSON.stringify(doc, null, 2)}\n`);
  process.stdout.write(
    `benchmark-lab: ${run.results.length} fixtures × ${run.arms.length} arms → ${outPath}\n`,
  );
  for (const a of run.aggregates) {
    process.stdout.write(
      `  ${a.arm.padEnd(12)} tokens=${a.total_tokens} calls=${a.total_calls} ` +
        `success=${a.success_count}/${a.fixtures} ` +
        `vs-baseline=${a.savings_vs_baseline_pct === null ? 'control' : `${a.savings_vs_baseline_pct}%`} ` +
        `cost=$${a.cost_usd.toFixed(4)}\n`,
    );
  }
} finally {
  cleanup();
}
