#!/usr/bin/env npx tsx
/**
 * Generate `docs/_data/response_tokens.json` — the aggregate token-reduction
 * figure the site and the README quote (TRA-904).
 *
 * It replaces `~40–50% on average`, which was never measured. TRA-880 showed
 * that figure's ancestor, `tokens_saved`, was `calls × RAW_COST_ESTIMATES[tool]
 * × 0.15` — a constant, booked before the tool ran, with zero variance across
 * thousands of calls. This joins three things that are each checkable:
 *
 *   1. `docs/perf/response-tokens.json` — real `o200k_base` counts of real
 *      `tools/call` responses over stdio (`scripts/bench-response-tokens.ts`).
 *   2. `benchmarks/response-tokens/call-volume.json` — the call mix those
 *      responses are weighted by, snapshotted from a real store, with
 *      provenance in the file.
 *   3. `RAW_COST_ESTIMATES` from `src/savings.ts` — the baseline, imported
 *      rather than retyped so it cannot drift away from the code.
 *
 * The baseline in (3) is STILL a hand-written estimate. The output says so in
 * `baseline_is_estimated`, every surface that quotes the figure has to repeat
 * it, and `tests/docs/savings-claims.test.ts` fails if one stops.
 *
 * Two ratios come out, and they are not interchangeable:
 *
 *   `reduction_pct`          net — losses subtracted. What a session actually costs.
 *   `credited_reduction_pct` losses floored at zero, which is what the corrected
 *                            counter books per call. Higher. Never the headline.
 *
 * ponytail: reads two committed files, writes one. Re-run it after either
 * changes:  npx tsx scripts/gen-response-tokens-data.ts
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { DEFAULT_RAW_COST, RAW_COST_ESTIMATES } from '../src/savings.js';

const REPO = fileURLToPath(new URL('..', import.meta.url));
const read = (p: string) => JSON.parse(readFileSync(join(REPO, p), 'utf-8'));

const bench = read('docs/perf/response-tokens.json') as {
  measured_at: string;
  target: string;
  rows: Array<{ tool: string; ok: boolean; real: number }>;
};
const volume = read('benchmarks/response-tokens/call-volume.json') as {
  read_at: string;
  source: string;
  calls_store_total: number;
  calls: Record<string, number>;
};

const rows = bench.rows
  .filter((r) => r.ok && volume.calls[r.tool] !== undefined)
  .map((r) => {
    const calls = volume.calls[r.tool];
    const baseline = RAW_COST_ESTIMATES[r.tool] ?? DEFAULT_RAW_COST;
    return {
      tool: r.tool,
      calls,
      baseline_per_call: baseline,
      measured_per_call: r.real,
      // >1 means the response costs more than the Read/Grep it replaces.
      measured_over_baseline: Number((r.real / baseline).toFixed(2)),
      baseline_tokens: calls * baseline,
      measured_tokens: calls * r.real,
    };
  })
  .sort((a, b) => b.calls - a.calls);

const missing = Object.keys(volume.calls).filter((t) => !rows.some((r) => r.tool === t));
if (missing.length) {
  throw new Error(
    `call-volume.json counts ${missing.join(', ')} but response-tokens.json has no ` +
      'successful measurement for them — re-run scripts/bench-response-tokens.ts',
  );
}

const sum = (f: (r: (typeof rows)[number]) => number) => rows.reduce((a, r) => a + f(r), 0);
const baselineTokens = sum((r) => r.baseline_tokens);
const measuredTokens = sum((r) => r.measured_tokens);
const creditedTokens = sum((r) => Math.max(0, r.baseline_tokens - r.measured_tokens));
const pct = (n: number) => Number(((n / baselineTokens) * 100).toFixed(1));

const out = {
  _comment:
    'Generated by scripts/gen-response-tokens-data.ts (TRA-904) — do not edit by hand. ' +
    'Every published aggregate savings figure reads from here. The measured side is ' +
    'real response tokens on the wire; the baseline side is still an estimate. Say both.',
  measured_at: bench.measured_at,
  measured_on: bench.target === 'self' ? "trace-mcp's own repository" : bench.target,
  volume_read_at: volume.read_at,
  volume_source: volume.source,
  baseline_is_estimated: true,
  tools_measured: rows.length,
  tools_costing_more: rows.filter((r) => r.measured_over_baseline > 1).length,
  calls_weighted: sum((r) => r.calls),
  calls_store_total: volume.calls_store_total,
  baseline_tokens: baselineTokens,
  measured_tokens: measuredTokens,
  reduction_pct: pct(baselineTokens - measuredTokens),
  credited_reduction_pct: pct(creditedTokens),
  rows,
};

// The output path is overridable so the regeneration check in
// tests/docs/savings-claims.test.ts can diff against a temp copy instead of
// rewriting the committed file underneath tests that read it in parallel.
writeFileSync(
  process.env.RESPONSE_TOKENS_OUT ?? join(REPO, 'docs/_data/response_tokens.json'),
  `${JSON.stringify(out, null, 2)}\n`,
);
console.log(
  `${out.reduction_pct}% net reduction over ${out.calls_weighted.toLocaleString('en-US')} calls ` +
    `(${out.credited_reduction_pct}% credited), ${out.tools_costing_more} of ${out.tools_measured} ` +
    'tools cost more than their baseline',
);
