/**
 * Laravel route extraction from route files.
 * Parses Route::get/post/resource/apiResource calls using regex on PHP source.
 */
import type { RawRoute } from '../../../../plugin-api/types.js';

/** HTTP methods supported by Laravel routing. */
const HTTP_METHODS = ['get', 'post', 'put', 'patch', 'delete', 'options', 'any'];

/** Resource route methods generated by Route::resource(). */
const RESOURCE_METHODS = [
  { method: 'GET', suffix: '', action: 'index' },
  { method: 'GET', suffix: '/create', action: 'create' },
  { method: 'POST', suffix: '', action: 'store' },
  { method: 'GET', suffix: '/{id}', action: 'show' },
  { method: 'GET', suffix: '/{id}/edit', action: 'edit' },
  { method: 'PUT', suffix: '/{id}', action: 'update' },
  { method: 'DELETE', suffix: '/{id}', action: 'destroy' },
];

/** API resource methods (no create/edit views). */
const API_RESOURCE_METHODS = RESOURCE_METHODS.filter(
  (m) => m.action !== 'create' && m.action !== 'edit',
);

export interface RouteExtractionResult {
  routes: RawRoute[];
  warnings: string[];
}

/**
 * Extract routes from a PHP route file source.
 * Handles Route::get/post/resource/apiResource patterns.
 */
export function extractRoutes(
  source: string,
  filePath: string,
): RouteExtractionResult {
  const routes: RawRoute[] = [];
  const warnings: string[] = [];

  // Extract use statements for class resolution
  const useMap = buildUseMap(source);

  // Extract simple route calls: Route::get('/path', [Controller::class, 'method'])
  extractSimpleRoutes(source, useMap, routes);

  // Extract Route::resource and Route::apiResource
  extractResourceRoutes(source, useMap, routes);

  // Extract middleware groups
  applyMiddlewareGroups(source, routes);

  return { routes, warnings };
}

/** Build a map of short class name -> FQN from `use` statements. */
function buildUseMap(source: string): Map<string, string> {
  const map = new Map<string, string>();
  const useRegex = /use\s+([\w\\]+?)(?:\s+as\s+(\w+))?;/g;
  let match: RegExpExecArray | null;
  while ((match = useRegex.exec(source)) !== null) {
    const fqn = match[1];
    const alias = match[2] ?? fqn.split('\\').pop()!;
    map.set(alias, fqn);
  }
  return map;
}

/** Resolve a class reference (e.g. UserController::class or \\App\\...::class) to FQN. */
function resolveClass(ref: string, useMap: Map<string, string>): string {
  // Short name first: UserController::class (no backslashes)
  const shortMatch = ref.match(/^(\w+)::class$/);
  if (shortMatch) {
    return useMap.get(shortMatch[1]) ?? shortMatch[1];
  }

  // Fully qualified: \App\Http\Controllers\PostController::class
  const fqnMatch = ref.match(/^\\?([\w\\]+)::class$/);
  if (fqnMatch) return fqnMatch[1];

  return ref;
}

/** Extract Route::get/post/put/patch/delete/any calls. */
function extractSimpleRoutes(
  source: string,
  useMap: Map<string, string>,
  routes: RawRoute[],
): void {
  const methodPattern = HTTP_METHODS.join('|');
  // Match: Route::get('/path', [Controller::class, 'method'])->name('x')->middleware('y')
  const regex = new RegExp(
    `Route::(${methodPattern})\\s*\\(\\s*['"]([^'"]+)['"]\\s*,\\s*\\[\\s*([\\w\\\\]+::class)\\s*,\\s*['"]([^'"]+)['"]\\s*\\]\\s*\\)([^;]*);`,
    'g',
  );

  let match: RegExpExecArray | null;
  while ((match = regex.exec(source)) !== null) {
    const method = match[1].toUpperCase();
    const uri = match[2];
    const controllerFqn = resolveClass(match[3], useMap);
    const action = match[4];
    const chain = match[5];

    const name = extractChainedName(chain);
    const middleware = extractChainedMiddleware(chain);

    routes.push({
      method,
      uri,
      name: name ?? undefined,
      controllerSymbolId: `${controllerFqn}::${action}`,
      middleware: middleware.length > 0 ? middleware : undefined,
    });
  }
}

/** Extract Route::resource and Route::apiResource calls. */
function extractResourceRoutes(
  source: string,
  useMap: Map<string, string>,
  routes: RawRoute[],
): void {
  const regex = /Route::(resource|apiResource)\s*\(\s*['"]([^'"]+)['"]\s*,\s*([\w\\]+::class)\s*\)([^;]*);/g;

  let match: RegExpExecArray | null;
  while ((match = regex.exec(source)) !== null) {
    const type = match[1];
    const prefix = match[2];
    const controllerFqn = resolveClass(match[3], useMap);
    const chain = match[4];
    const middleware = extractChainedMiddleware(chain);

    const methods = type === 'apiResource' ? API_RESOURCE_METHODS : RESOURCE_METHODS;

    for (const rm of methods) {
      routes.push({
        method: rm.method,
        uri: `/${prefix}${rm.suffix}`,
        name: `${prefix}.${rm.action}`,
        controllerSymbolId: `${controllerFqn}::${rm.action}`,
        middleware: middleware.length > 0 ? middleware : undefined,
      });
    }
  }
}

/** Extract ->name('...') from method chain. */
function extractChainedName(chain: string): string | null {
  const match = chain.match(/->name\s*\(\s*['"]([^'"]+)['"]\s*\)/);
  return match ? match[1] : null;
}

/** Extract ->middleware('...') or ->middleware(['...', '...']) from method chain. */
function extractChainedMiddleware(chain: string): string[] {
  const match = chain.match(/->middleware\s*\(\s*(['"\[].*?)\s*\)/);
  if (!match) return [];

  const arg = match[1];
  // Array form: ['auth', 'verified']
  if (arg.startsWith('[')) {
    const items: string[] = [];
    const regex = /['"]([^'"]+)['"]/g;
    let m: RegExpExecArray | null;
    while ((m = regex.exec(arg)) !== null) {
      items.push(m[1]);
    }
    return items;
  }

  // Single string: 'auth'
  const single = arg.match(/['"]([^'"]+)['"]/);
  return single ? [single[1]] : [];
}

/** Apply middleware from Route::middleware('...')->group(...) wrappers. */
function applyMiddlewareGroups(source: string, routes: RawRoute[]): void {
  // Match: Route::middleware('auth:sanctum')->group(function () { ... });
  const groupRegex = /Route::middleware\s*\(\s*['"]([^'"]+)['"]\s*\)\s*->\s*group\s*\(\s*function\s*\([^)]*\)\s*\{([\s\S]*?)\}\s*\)/g;

  let match: RegExpExecArray | null;
  while ((match = groupRegex.exec(source)) !== null) {
    const groupMiddleware = match[1];
    const groupBody = match[2];

    // Find routes defined inside this group by matching their URIs
    for (const route of routes) {
      // Check if this route's definition appears inside the group body
      if (groupBody.includes(route.uri)) {
        route.middleware = route.middleware
          ? [groupMiddleware, ...route.middleware]
          : [groupMiddleware];
      }
    }
  }
}
